CREATE TABLE ENTRIES
(
	ID INT PRIMARY KEY	AUTO_INCREMENT,
	LOGIN varchar(50) NOT NULL,
	USERNAME varchar(50) NOT NULL,
	PASSWORD varchar(50) NOT NULL
);
INSERT INTO ENTRIES(LOGIN,PASSWORD) VALUES('ADMIN','ADMIN');